### ISSUE TITLE
foundry latest version for pf2 module

### ISSUE THREAD

**Issue by Myriade91** [L-PLS/dual-chat-tabs#1]
Seems when i activate dual chat tab, i can't roll damage anymore.

**Comment by L-PLS** [comment]
In order for me to understand the situation that is happening to you, you must include the following information.
(1) Foundry VTT version and build number
(2) Game system and its version number
(3) Minimum mod configuration that the phenomenon reproduces(If you turn off the mods one by one, you should be able to identify the affected mods)

I do not use pf2 system, so please be as accurate as possible.

**Comment by Myriade91** [comment]
1 : V10 291
2 : Pathfinder 2 version 4.5.0
3 : even with all others mods not active i have the problem.

**Comment by L-PLS** [comment]
I have tested it with the version you contacted me with. But I could not reproduce the situation. The procedure was to create a PF2 world, then I set up the mod with only one "Dual- chat-tab". Then I created a character, selected Unarmed Attack from the character sheet and did a hit decision. The result appeared in the chat column and I pressed the Damege button that appeared there. The result of the damage was displayed in the chat. I added Bastard Sword from Compedium besides Unarmed Attack and did the same procedure, the damage result was shown in the chat box. I also created another user besides Gamemaster and did the same, but the result did not change.
Can you reproduce the situation with the same procedure as I did? Or are you referring to a different damage roll that you wrote about?
![version](https://user-images.githubusercontent.com/106317364/208301523-e782e33b-7910-4311-b83e-9028720eb6df.jpg)
![dmageroll](https://user-images.githubusercontent.com/106317364/208301532-340796a1-ada2-4f0e-b0bc-77fd8fb1bb4c.jpg)

**Comment by L-PLS** [comment]
I have continued to verify and found out.
The game master makes a hit decision using the tokens of the character the user owns. Then, there is no response when pressing the damage button on the chat card with the result displayed.
It seems that a new feature I added in Dual-chat-tabs causes internal interference in the PF2 system. This feature can be turned off from the settings screen. You can refer to the attached image.
It is possible that this internal interference is specific to PF2, as a similar process does not cause problems in the D&D system. I will look into getting this to work correctly with the feature turned on. However, you should turn the feature off once to work around the situation.
![user](https://user-images.githubusercontent.com/106317364/208332667-ede0be8b-f179-4814-a780-6c12a411c8c0.jpg)
![setting](https://user-images.githubusercontent.com/106317364/208332678-0f51e3ba-b738-43c7-9a0a-34f1cd61be38.jpg)

**Comment by Myriade91** [comment]
Thanks ! Awesome ! It works again. Keep up the good work !
